language: php

services:
  - memcached
  - redis-server

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  matrix:
    - APP_CACHE=filesystem setup=lowest
    - APP_CACHE=memcached setup=lowest
    - APP_CACHE=predis setup=lowest
    - APP_CACHE=array setup=lowest
    - APP_CACHE=filesystem setup=highest
    - APP_CACHE=memcached setup=highest
    - APP_CACHE=predis setup=highest
    - APP_CACHE=array setup=highest

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [ "$APP_CACHE" = "memcached" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ -z "$setup" ]; then composer install; fi;
  - if [ "$setup" = "lowest" ]; then composer update --prefer-lowest --no-interaction --prefer-dist --no-suggest; fi;
  - if [ "$setup" = "highest" ]; then composer update --no-interaction --prefer-dist --no-suggest; fi;

script: vendor/bin/phpunit
